# Generated by Django 6.0.3 on 2026-04-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('stadium', 'Mini-stadion'), ('playstation', 'Playstation'), ('pc_club', 'Kompyuter klub'), ('billiard', 'Billiard')], default='stadium', max_length=50),
        ),
    ]
