# Generated by Django 6.0.3 on 2026-04-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headapp', '0003_alter_location_options_location_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='location',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='location',
            name='price',
        ),
        migrations.RemoveField(
            model_name='location',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('stadium', 'Mini-stadion'), ('playstation', 'Playstation'), ('pc_club', 'Kompyuter klub'), ('billiard', 'Billiard')], default='stadium', max_length=50),
        ),
        migrations.DeleteModel(
            name='LocationImage',
        ),
    ]
