# Generated by Django 6.0.3 on 2026-04-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headapp', '0002_location_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-created_at'], 'verbose_name': 'Joylashuv', 'verbose_name_plural': 'Joylashuvlar'},
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Soatlik narx (so'mda)", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('stadium', 'Mini-stadium'), ('playstation', 'Playstation'), ('pc_club', 'PC Club'), ('billiard', 'Billiard')], default='stadium', max_length=50),
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='locations/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Tartib raqami (0 = birinchi)')),
                ('is_cover', models.BooleanField(default=False, help_text='Muqova rasmi')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='headapp.location')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
