# Generated by Django 6.0.3 on 2026-05-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headapp', '0004_alter_location_options_remove_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
